MODULE VARIABLES
IMPLICIT NONE
INTEGER :: N,NN,NPASOS=100000
REAL*8 :: RHO,LX,LY,DX,DY,RIJ,UPOT,ULJ,M_X,M_Y,UKIN,DELTA_T,R_CUT
REAL*8 :: SGM = 1.0, EPS=1.0
REAL*8, DIMENSION(:), ALLOCATABLE::RX,RY
REAL*8, DIMENSION(:), ALLOCATABLE::VX,VY
REAL*8, DIMENSION(:), ALLOCATABLE::FX,FY
REAL*8 RND
END MODULE VARIABLES

PROGRAM MD_F
USE VARIABLES
IMPLICIT NONE
CALL COORDENADAS
CALL CELDA
CALL FUERZAS
CALL MDLOOP
END PROGRAM MD_F

SUBROUTINE COORDENADAS
USE VARIABLES
IMPLICIT NONE
INTEGER :: I,J,K,M

OPEN(3,FILE='input.txt',STATUS='OLD',ACTION='READ')
READ(3,*)
READ(3,*)
READ(3,*)NPASOS
READ(3,*)N
READ(3,*)RHO
READ(3,*)DELTA_T
READ(3,*)R_CUT
READ(3,*)
CLOSE(3)

ALLOCATE(RX(N),RY(N))
ALLOCATE(VX(N),VY(N))
ALLOCATE(FX(N),FY(N))

LX = SQRT(DBLE(N/RHO))
LY = LX
NN = SQRT(DBLE(N)) + 1 
DX = LX/DBLE(NN)
DY = DX
K=0
DO I=1,NN 
     DO J=1,NN
         IF(K<N) THEN
             K=K+1
             RX(K) = DBLE(I) * DX
             RY(K) = DBLE(J) * DY
         END IF
     END DO
END DO
M_X = 0.0
M_Y = 0.0
DO I =1, N
    CALL RANDOM_NUMBER(RND)
    VX(I) = 2.0 * RND - 1.0
    VY(I) = 2.0 * RND - 1.0
    M_X = M_X + VX(I)
    M_Y = M_Y + VY(I)
END DO
M_X = M_X / DBLE(N)
M_Y = M_Y / DBLE(N)
DO I = 1, N
    VX(I) = VX(I)-M_X
    VY(I) = VY(I)-M_Y
END DO
END SUBROUTINE COORDENADAS

SUBROUTINE CELDA
USE VARIABLES
IMPLICIT NONE
INTEGER :: I
OPEN(1,FILE='COORDENADAS.xyz', STATUS='UNKNOWN', ACTION='WRITE')
WRITE(1,*) N
WRITE(1,*)
DO I=1,N
    WRITE(1,*)'C ', RX(I), RY(I), 0.0
END DO
CLOSE(1)
END SUBROUTINE CELDA

! SUBRUTINA A REVISAR

SUBROUTINE FUERZAS
USE VARIABLES
IMPLICIT NONE
INTEGER :: I, J
REAL*8 :: DULJ
DO I=1, N
    FX(I) = 0.0
    FY(I) = 0.0
END DO
UPOT = 0.0
DO I = 1, NN - 1
 DO J = I+1, NN
     DX = RX(I) - RX(J)
     DY = RY(I) - RY(J)
! MINIMA IMAGEN
IF(DX > 0.5*LX) THEN
    DX = DX - LX
ELSEIF(DX < -0.5*LX) THEN
    DX = DX + LX
ENDIF 
IF(DY > 0.5*LY) THEN
    DY = DY - LY
ELSEIF(DY < -0.5*LY) THEN
    DY = DY + LY
ENDIF 
!
     RIJ = SQRT(DX * DX + DY * DY)
      IF (RIJ<= R_CUT) THEN
!           ULJ = 4.0 * EPS * ((SGM/RIJ)**6 * ( (SGM/RIJ)**6 - 1.0)) - UCUT
           ULJ = 4.0 * EPS * ((SGM/RIJ)**6 * ( (SGM/RIJ)**6 - 1.0)) 
           UPOT = UPOT + ULJ
           DULJ = 48.0 * EPS * (SGM/RIJ)**6 * ((SGM/RIJ)**6 - 0.5)/(RIJ * RIJ)
           FX(I) = FX(I) + DULJ * DX
           FY(I) = FY(I) + DULJ * DY
           FX(J) = FX(J) - DULJ * DX
           FY(J) = FY(J) - DULJ * DY
        END IF
 END DO 
END DO
!WRITE(*,*) SUM(FX),SUM(FY)
!STOP
END SUBROUTINE FUERZAS
! 
SUBROUTINE MDLOOP
USE VARIABLES
IMPLICIT NONE
REAL*8 :: UTOT
INTEGER :: I, PASO
OPEN(2,FILE='ENERGIAS.DAT', STATUS='UNKNOWN', ACTION='WRITE') 
DO PASO = 1, NPASOS
    DO I =1, N
        VX(I) = VX(I) + 0.50 * DELTA_T * FX(I)
        VY(I) = VY(I) + 0.50 * DELTA_T * FY(I)
        RX(I) = RX(I) + DELTA_T *VX(I)
        RY(I) = RY(I) + DELTA_T *VY(I)
        ! CONDICIONES PERIODICAS A LA FRONTERA 
        IF(RX(I) < 0.0) RX(I) = RX(I) + LX
        IF(RY(I) < 0.0) RY(I) = RY(I) + LY
        IF(RX(I) > 0.0) RX(I) = RX(I) - LX
        IF(RY(I) > 0.0) RY(I) = RY(I) - LY
    END DO
    CALL FUERZAS
    UKIN=0.0
    DO I =1, N
        VX(I) = VX(I) + 0.50 * DELTA_T * FX(I)
        VY(I) = VY(I) + 0.50 * DELTA_T * FY(I)
        UKIN = UKIN + VX(I) ** 2 + VY(I)**2 
    END DO
    IF(MOD(PASO,100)== 0) CALL CELDA
    UKIN = UKIN * 0.50
    UTOT = UPOT + UKIN
    WRITE(*,'(I7,X,3F12.6)')PASO,UPOT/DBLE(N),UKIN/DBLE(N),UTOT/(DBLE(N))
    WRITE(2,'(I7,X,3F12.6)')PASO,UPOT/DBLE(N),UKIN/DBLE(N),UTOT/(DBLE(N))
END DO
CLOSE(2)
END SUBROUTINE MDLOOP
