PROGRAM HISTOGRAMA
IMPLICIT NONE
REAL*8 :: DELTA,LI,LS,VX
INTEGER, DIMENSION(:), ALLOCATABLE::FREQ
INTEGER :: I, BIN, NO_BINS, NAT=10, SUMA_FREQ
LS = 10.0
LI = 0.0
NO_BINS = 10
DELTA = (LS - LI) / NO_BINS
ALLOCATE(FREQ(NAT))
DO I = 1, NAT
    OPEN(1,FILE='datos_histograma-p.txt',STATUS='OLD',ACTION='READ')
    READ(1, *) VX
    BIN = VX / DELTA
    FREQ(BIN) = FREQ(BIN) + 1
END DO
CLOSE(1)

SUMA_FREQ = 0.0
DO I = 1, NO_BINS
    OPEN(2,FILE='salida_histograma.dat',STATUS='UNKNOWN',ACTION='WRITE')
    SUMA_FREQ = FREQ(I) + SUMA_FREQ
    WRITE(2,*) I * DELTA, FREQ(I)
END DO
CLOSE(2)

IF(SUMA_FREQ .NE. NAT) THEN
    WRITE(*,*) 'WRONG DATA. CHECK YOUR CODE!', SUMA_FREQ
ELSE
    WRITE(*,*) SUMA_FREQ
ENDIF

END PROGRAM HISTOGRAMA
