MODULE VARIABLES
IMPLICIT NONE
INTEGER :: N,NN
REAL*8 RHO, LX, LY, L, DX, DY 
REAL*8, DIMENSION(:), ALLOCATABLE::RX, RY
END MODULE VARIABLES

PROGRAM MD_1
USE VARIABLES
IMPLICIT NONE
CALL COORDENADAS
CALL CELDA
END PROGRAM MD_1

SUBROUTINE COORDENADAS
USE VARIABLES
IMPLICIT NONE
INTEGER :: I,J,K
WRITE(*,*) 'DAME EL NUMERO DE ATOMOS'
READ(*,*) N
ALLOCATE(RX(N),RY(N))
WRITE(*,*) 'DAME LA DENSIDAD'
READ(*,*) RHO
LX = SQRT(DBLE(N)/RHO)
LY = LX
L = LX
NN = SQRT(DBLE(N)) + 1
DX = LX / DBLE(NN)
DY = LY / DBLE(NN)
K=0
DO I=1, NN
 DO J=1,NN
 IF(K<N) THEN
     K=K+1
     RX(K) = DBLE(I) * DX
     RY(K) = DBLE(J) * DY 
 END IF
 END DO
END DO
END SUBROUTINE COORDENADAS

SUBROUTINE CELDA
USE VARIABLES
IMPLICIT NONE
INTEGER :: I
CHARACTER(len=12) :: filename
filename = 'COORD-py.xyz'
OPEN(1,FILE=filename, STATUS='REPLACE', ACTION='WRITE')
DO I=1,N
    WRITE(1,*)'pos=vector(', RX(I),',', RY(I),',', 0,')'
END DO
CLOSE(1)
END SUBROUTINE CELDA
