MODULE VARIABLES
IMPLICIT NONE
INTEGER :: N,NN
REAL*8 RHO, LX, LY, L, DX, DY 
REAL*8, DIMENSION(:), ALLOCATABLE::RX, RY
END MODULE VARIABLES

PROGRAM MD_1
USE VARIABLES
IMPLICIT NONE
CALL COORDENADAS
CALL CELDA
END PROGRAM MD_1

SUBROUTINE COORDENADAS
USE VARIABLES
IMPLICIT NONE
INTEGER :: I,J
INTEGER :: U, V
!WRITE(*,*) 'DAME EL NUMERO DE ATOMOS'
!READ(*,*) N
N = 4
RHO = 1.0
ALLOCATE(RX(N),RY(N))
!WRITE(*,*) 'DAME LA DENSIDAD'
!READ(*,*) RHO
LX = SQRT(DBLE(N)/RHO)
LY = LX
L = LX
NN = SQRT(DBLE(N)) + 1
DX = LX / DBLE(NN)
DY = LY / DBLE(NN)
U = 0 
V = U
DO J = 0, N
 V = V + 1
 DO I = 0, N
 U = U + 1
     IF ( U <= N ) THEN
         RX(U) = DBLE(I) * DX
     END IF
 END DO 
 IF ( V <= N ) THEN
     RY(V) = DBLE(J) * DY
 END IF
END DO 
END SUBROUTINE COORDENADAS

SUBROUTINE CELDA
USE VARIABLES
IMPLICIT NONE
INTEGER :: I
CHARACTER(len=12) :: filename
filename = 'COORD-py.xyz'
OPEN(1,FILE=filename, STATUS='REPLACE', ACTION='WRITE')
DO I=1,N
    WRITE(1,*)'pos=vector(', RX(I),',', RY(I),',', 0,')'
END DO
CLOSE(1)
END SUBROUTINE CELDA
