PROGRAM SUMA_MPI
<<<<<<< HEAD
use mpi
IMPLICIT NONE
!INCLUDE "mpif.h"
INTEGER :: N = 100, I, SUMA
INTEGER :: NPROCS, MASTER = 0, ESCLAVO, ERROR,INICIO, FIN

CALL MPI_INIT(ERROR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NPROCS, ERROR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD,ESCLAVO, ERROR)

INICIO = (ESCLAVO * N) / NPROCS + 1
FIN = (ESCLAVO + 1) * N / NPROCS

WRITE(*,*) INICIO, FIN
DO I = INICIO, FIN
    SUMA = SUMA + 1
END DO

=======
USE MPI
IMPLICIT NONE

INTEGER :: N = 100, I, SUMA
INTEGER, DIMENSION(:), ALLOCATABLE::RESULTADO
INTEGER :: NPROCS, MASTER = 0, ESCLAVO, ERROR,INICIO, FIN

CALL MPI_INIT(ERROR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, ERROR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, ESCLAVO, ERROR)

INICIO = (ESCLAVO * N) / NPROCS + 1
FIN = (ESCLAVO + 1) * N / NPROCS

ALLOCATE(RESULTADO(N))
SUMA = 0
DO I = INICIO, FIN
    RESULTADO(I) = I 
    SUMA = RESULTADO(I) + SUMA
END DO

WRITE(*,*) "RESULTADO PARA ESCLAVO ", ESCLAVO,SUMA

>>>>>>> c239e6585439a6c28ae85129a895ab09fa914c59
CALL MPI_FINALIZE(ERROR)

END PROGRAM SUMA_MPI
