PROGRAM SUMA_MPI
USE MPI
IMPLICIT NONE

INTEGER :: N = 100, I, SUMA

INTEGER :: NPROCS, MASTER = 0, ESCLAVO, ERROR,INICIO, FIN

CALL MPI_INIT(ERROR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, ERROR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, ESCLAVO, ERROR)

INICIO = (ESCLAVO * N) / NPROCS + 1
FIN = (ESCLAVO + 1) * N / NPROCS

WRITE(*,*) ESCLAVO, INICIO, FIN

DO I = INICIO, FIN
    SUMA = SUMA + 1
END DO

CALL MPI_FINALIZE(ERROR)

END PROGRAM SUMA_MPI
