PROGRAM SUMA_MPI_P_I
USE MPI
IMPLICIT NONE

INTEGER :: N = 100, I, SUMA
integer, dimension(:), allocatable::resultado
INTEGER :: NPROCS, MASTER = 0, ESCLAVO, ERROR, INICIO, FIN

CALL MPI_INIT(ERROR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, ERROR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, ESCLAVO, ERROR)

INICIO = (ESCLAVO * N) / NPROCS + 1
FIN = (ESCLAVO + 1) * N - 1

! SUMA IMPARES
ALLOCATE(resultado(N))
suma = 0
DO I = INICIO, FIN - 2 , 2
   SUMA = resultado(i) + suma
END DO

WRITE(*,*) "RESULTADO PARA ESCLAVO ", ESCLAVO,SUMA

CALL MPI_FINALIZE(ERROR)

END PROGRAM SUMA_MPI_P_I
