PROGRAM HISTOGRAMA
IMPLICIT NONE
REAL*8 :: DELTA,VX
INTEGER, DIMENSION(:), ALLOCATABLE::FREQ
INTEGER :: LS, LI, I, BIN, NO_BINS, NAT=180
LS = 180
LI = 1
NO_BINS = 100
DELTA = (LS - LI) / NO_BINS
ALLOCATE(FREQ(NAT))
DO I = 1, NAT
    OPEN(1,FILE='datos.dat',STATUS='OLD',ACTION='READ')
    READ(1, *) VX
    BIN = VX / DELTA
    FREQ(BIN) = FREQ(BIN) + 1
END DO
CLOSE(1)

DO I = 1, NAT
    OPEN(2,FILE='salida_histograma.dat',STATUS='UNKNOWN',ACTION='WRITE')
    WRITE(2,*) int(I * DELTA) , FREQ(I)
END DO
CLOSE(2)

END PROGRAM HISTOGRAMA
