PROGRAM SUMA_MPI
USE MPI
IMPLICIT NONE

INTEGER :: N = 100, I, SUMA
INTEGER :: STATUS(MPI_COMM_WORLD) 
INTEGER :: NPROCS, MASTER = 0, ESCLAVO, ERROR,INICIO, FIN, RESULTADO=0

CALL MPI_INIT(ERROR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, ERROR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, ESCLAVO, ERROR)

INICIO = (ESCLAVO * N) / NPROCS + 1
FIN = (ESCLAVO + 1) * N / NPROCS

SUMA=0
DO I = INICIO, FIN
    SUMA = SUMA + i
END DO

IF(ESCLAVO == MASTER) THEN
  CALL MPI_SEND(SUMA, 1, MPI_INTEGER, 1, 100, MPI_COMM_WORLD,ERROR)
  WRITE(*,*) "MANDA", ESCLAVO, SUMA
ELSE IF (ESCLAVO == 1) THEN
  CALL MPI_RECV(RESULTADO, 1, MPI_INTEGER, MASTER, 100, MPI_COMM_WORLD, STATUS, ERROR)
  ESCLAVO = 1
  WRITE(*,*) "RECIVE", ESCLAVO, RESULTADO+SUMA
END IF

CALL MPI_FINALIZE(ERROR)
END PROGRAM SUMA_MPI
